version: '3'

networks:
  zabbix-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20

services:
  placeholder:
    image: busybox
    networks:
      - zabbix-net
