version: '3'

services:
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    container_name: zabbix-server-mysql
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
      ZBX_JAVAGATEWAY: "zabbix-java-gateway"
    networks:
      - zabbix-net
    ports:
      - "10051:10051"
    restart: unless-stopped

networks:
  zabbix-net:
    external: true
